version: '3.4'

services:
  postgres:
    image: postgres:11.0
    restart: always
    environment:
      POSTGRES_DB: mis
      POSTGRES_USER: mis
      POSTGRES_PASSWORD: mis
    ports:
      - 5432:5432